name: CI
on: [ push, pull_request ]
jobs:
  Build:
    name: Build image and push SNAPSHOT from main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint Connector Runtime Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: runtime/Dockerfile

    - name: Lint Connector Bundle Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: bundle/Dockerfile

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.2
      if: github.ref == 'refs/heads/main'
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false # we rely on step outputs, no need for environment variables
        secrets: |
          secret/data/products/connectors/ci/common DOCKERHUB_USER;
          secret/data/products/connectors/ci/common DOCKERHUB_PASSWORD;

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        username: ${{ steps.secrets.outputs.DOCKERHUB_USER }}
        password: ${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}

    - name: Build and Push Runtime Docker Image tag SNAPSHOT
      uses: docker/build-push-action@v3
      with:
        context: runtime/
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: camunda/connectors:SNAPSHOT

    - name: Build and Push Docker Image tag SNAPSHOT
      uses: docker/build-push-action@v3
      with:
        context: bundle/
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: camunda/connectors-bundle:SNAPSHOT
